[build]
  base = "flutter_app"
  publish = "flutter_app/build/web"
  command = """
    git clone https://github.com/flutter/flutter.git --branch stable --depth 1 $HOME/flutter && \
    export PATH="$HOME/flutter/bin:$PATH" && \
    flutter doctor -v && \
    flutter pub get && \
    flutter build web --release
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
